### ISSUE TITLE
New Oracle image

### ISSUE THREAD

**Issue by bcogrel** [ontop/ontop-dockertests#13]
Based on Oracle XE (express edition)  18.4 (18c)

## Creating the Oracle base image

Instructions on
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md#running-oracle-database-18c-express-edition-in-a-docker-container

Oracle XE can be found at:
https://www.oracle.com/database/technologies/xe-downloads.html

## Creating ontop-oracle
From the Oracle base image available locally on the machine

# TODO
- [x] Create the Oracle base image and document how to proceed
- [x] Update the Dockerfile for ontop-oracle
   * [x] Require the env variable LICENSE to be bound and to match "accept" (like for DB2)
- [x] Insert a link to the XE license in the README https://www.oracle.com/downloads/licenses/db18c-express-license.html
- [x] Publish it on Docker Hub
